### ISSUE TITLE
Disable NTLM + Disable NLA vs. set NTLMv2 only (keeping NLA) vs doing nothing

### ISSUE THREAD

**Issue by 29039** [DigitalRuby/IPBan#117]
Hi Jeff, thanks again.

I'm just curious what the rationale is behind this advice. 

My understanding is that the NLA is an extra level of security where RDP needs to get Authenticated before it will even draw the login window for the user to see and log into. This helps in case there is a security vulnerability in the display protocol itself, so that a vulnerable RDP could still protected because NLA is mitigating the vulnerability.

There have been a few cases in the past where there has been an RDP vulnerability, but users were saved by NLA until the patch was installed, while users with NLA disabled got compromised. It was a vulnerability in the protocol itself, not a brute force of the logins, so IPBan wouldn't have helped.

Keep in mind that IPBan is a tool where many users are using it to protect RDP, as an alternative or in addition to VPN.

So it seems a bit counterintuitive that the main advice is to disable NLA.

Wouldn't the alternate solution which keeps NLA be better?

And does IPBan still work properly if the user doesn't make the change at all?

Maybe you know more than me on this and I'm horribly mistaken.

Thanks in advance.

**Comment by jjxtra** [comment]
NLA is an extra layer of security. The problem is, if you disable NTLM and enable NLA, you will be unable to RDP into your box, regardless of the client Windows version.

I've tried all the Microsoft recommendations for making sure the appropriate group policies are set, etc. but so far I don't have a work-around. I always get a weird credssp error if I disable NTLM and keep NLA enabled.

So you can have NLA with insecure NTLM which doesn't log ip addresses, or you can turn off NLA and turn off NTLM and ensure that all ip addresses are logged properly.

Another quirk- On Windows Server 2012 with NLA on, ip addresses are not logged properly regardless of NTLM setting.

NLA reduces system resources used at login by a small amount by not creating a session, but other than that there is not much difference in security.

**Comment by 29039** [comment]
So to confirm, if NLA is enabled (assuming Windows 10/Server 2016+), it might be possible for an attacker to still bruteforce on an NLA level, as IPBan is unable to protect against that because Windows does not log the IP address when that happens?

Keep in mind, my perspective is protecting against 0days or 1days where the patch hasn't been installed yet, as RDP is a popular target for this sort of thing. Maybe VPN, etc. and other extra layers is the answer for that, but every tool helps.

**Comment by jjxtra** [comment]
For Server 2016 and Win 10 it's fine, it's only Windows Server 2012/Windows 8 that have the ip logging issue.

**Comment by RoboMWM** [comment]
I'm also trying to understand the recommendations in the Readme, as it seems to suggest multiple things...?

`Network Security: Restrict NTLM: Incoming NTLM Traffic` I'm assuming this doesn't work with NLA enabled because it's blocking both NTLM and NLTMv2, and NLA uses this?

The response here is also a tad confusing, not sure if you're referring to NTLM (v1) or NTLM itself (including both v1 and v2).
