### ISSUE TITLE
Public Banned IP Database

### ISSUE THREAD

**Issue by jjxtra** [DigitalRuby/IPBan#59]
I've had multiple people asking about when a public database of banned ip addresses will be available. My answer is that I am working on it, slowly, trying to figure out how to make it a good database that does not have false positives, etc. This project is open source and I have currently done it all in my spare time. Donations are extremely rare.

To help get more advanced features available, I am planning on offering a paid version hopefully within a year or so that offers a lot more features, server management and reporting tools and more.

Stay tuned and please visit <a href='https://ipban.com'>ipban.com</a> for updates.

**Comment by ddominq** [comment]
Firstly, thank you very much for this program.
His installation on widows 10 especially on the home edition version is a bit different from the one described https://github.com/DigitalRuby/IPBan
1. the command pasted in CMD regarding the Change Local Security Policy does not work, but you can install https://github.com/Fleex255/PolicyPlus/issues/16 and run secpol.msc and switch to logging in both necessary scenarios.
Maybe someone will be useful.

My question:
What should be added in ipban.config to block attempts to log on to the tvnserver (VNC) under the same conditions as for RDP?

I think you can successfully sell an IP database collected by users. Network and hardware administrators certainly have bdudgets for such purchases.
For example, I have 829 total ip addresses in the ipban.sqlite database. Collected from 3.17.2019
Respect

**Comment by jjxtra** [comment]
Does VNC write to a log file or the event viewer? If so can you paste in a few entries? You can x out user names and ip addresses if you want.

**Comment by ddominq** [comment]
Logs in as tvnserver source.
Attached example. This machine already has an "ipban" with a filter on the
RDP.
Dominik


wt., 14 maj 2019 o 15:49 Jeff Johnson <notifications@github.com> napisał(a):

**Comment by jjxtra** [comment]
Not sure what happened to the last message, it looks garbled and I don't see an attachment

**Comment by ddominq** [comment]
Again, this time through a link to the cloud
https://drive.google.com/open?id=0B_mZjusDZ4etWHN1RzJzd2FXYzAyY09BTlhHblQzRGcwclRz
Regards
Dominik


wt., 14 maj 2019 o 16:55 Jeff Johnson <notifications@github.com> napisał(a):

**Comment by jjxtra** [comment]
That appears to have worked, thanks I will look at this and add to the default configuration.

**Comment by jjxtra** [comment]
Do you have any with a successful login in them?

**Comment by ddominq** [comment]
https://drive.google.com/open?id=1YtHpCZcwhapAzDalJeHSsGITQAz6qmQU
Here is the whole login of the tvnserver service.
As you can see the disconnection because of the password and login logon as
only information.
"I will look at this configuration." great news!

Good luck
Dominik


wt., 14 maj 2019 o 17:04 Jeff Johnson <notifications@github.com> napisał(a):

**Comment by ddominq** [comment]
Recipe for your own brute force tvnserver service attack logs.
Download and install on your honeypot, free tightVNC
https://www.tightvnc.com/download.php
Install serwer with default TCP 5900 port
Open and redirect TCP port 5900 on tour router
If you have public IP after few hours you will notice the first login
attempts.
The reason for the popularity is simple ... If you are looking for a
program against brute force attacks on VNC, you will find ready scripts and
programs ... to attack.
https://www.google.com/search?ei=0t7aXKS8AqmQmwXQt5iYAg&q=vnc+brute+force+software&search_plus_one=form&oq=vnc+brute+force+software&gs_l=psy-ab.12...9384.11274..13096...0.0
..0.241.1684.0j7j2 ...... 0 .... 1..gws-visas .......
0i19j0i22i30i19j0i22i30j33i21.An47FSfy230
Your program is rare in this matter

Dominik

wt., 14 maj 2019 o 17:19 Dominik <ddominiq@gmail.com> napisał(a):

**Comment by jjxtra** [comment]
IPBan 1.4.6 download is ready, try it out, it *should* block VNC failures automatically now. Let me know how it goes...

**Comment by ddominq** [comment]
something is wrong with the config
2019-05-14 18:19:02.7488|WARN|DigitalRuby.IPBan.IPBanLog|Login failure:
104.248.243.148, , VNC, 1
2019-05-14 18:19:17.7805|WARN|DigitalRuby.IPBan.IPBanLog|Forgetting ip
address 104.248.243.148, time expired
I set
<add key="BanTime" value="00:00:00:00"/> (forever)
<add key="ExpireTime" value="00:00:00:00"/> (forever)
after put my old database ipban.sqlite in new installation and restart
service at start delete all IP
1. 0 total ip addresses in the ipban.sqlite database
"Stopped IPBan service
2019-05-14 18:28:54.7704|WARN|DigitalRuby.IPBan.IPBanLog|549 total ip
addresses in the ipban.sqlite database
(...)
2019-05-14 18:28:55.5355|WARN|DigitalRuby.IPBan.IPBanLog|Un-banning ip
address {0}, ban expired"


wt., 14 maj 2019 o 17:37 Jeff Johnson <notifications@github.com> napisał(a):

**Comment by jjxtra** [comment]
I don't recommend banning forever, but if you want a long ban time, set the ban and expire to something like 60 days. But doing it for "forever" will continue to grow in memory usage and processing requirements.

**Comment by jjxtra** [comment]
If you re-download the same file, I have fixed it to accept a 0 timespan as "forever".

**Comment by ddominq** [comment]
Sample:

start service
2019-05-14 18:53:55.1754|WARN|DigitalRuby.IPBan.IPBanLog|Log levels:
True,True,True,False,False,False
testing
2019-05-14 18:56:10.2699|WARN|DigitalRuby.IPBan.IPBanLog|Login failure:
178.42.112.106, admin, RDP, 1
2019-05-14 18:56:25.2930|WARN|DigitalRuby.IPBan.IPBanLog|Forgetting ip
address 178.42.112.106, time expired
2019-05-14 18:56:40.3262|WARN|DigitalRuby.IPBan.IPBanLog|Login failure:
178.42.112.106, admin, RDP, 2
2019-05-14 18:56:40.3262|WARN|DigitalRuby.IPBan.IPBanLog|Banning ip
address: 178.42.112.106, user name: admin, config black listed: False,
count: 2, extra info:
?
2019-05-14 18:56:55.4010|WARN|DigitalRuby.IPBan.IPBanLog|Un-banning ip
address {0}, ban expired
2019-05-14 18:56:55.4174|WARN|DigitalRuby.IPBan.IPBanLog|Clearing all block
firewall rules because ipban.sqlite is empty
2019-05-14 18:58:55.5481|WARN|DigitalRuby.IPBan.IPBanLog|Login failure:
104.248.243.148, , VNC, 1
?
2019-05-14 18:59:10.5811|WARN|DigitalRuby.IPBan.IPBanLog|Forgetting ip
address 104.248.243.148, time expired
2019-05-14 19:03:55.8430|WARN|DigitalRuby.IPBan.IPBanLog|Login failure:
104.248.243.148, , VNC, 1
?
2019-05-14 19:04:10.8719|WARN|DigitalRuby.IPBan.IPBanLog|Forgetting ip
address 104.248.243.148, time expired

which file should replace?

wt., 14 maj 2019 o 18:47 Jeff Johnson <notifications@github.com> napisał(a):

**Comment by ddominq** [comment]
I set it forever, because the program does not assume the rule "IPBan_0" in
the windows firewall and the last update 17763.475 does not transfer the
rules from the old version windows.
IPBAN scares that he deletes "2019-05-14 18: 56: 55.4174 | WARN |
DigitalRuby.IPBan.IPBanLog | Clearing all block firewall rules because
ipban.sqlite is empty"
Fortunately, nothing erases in the firewall
Dominik


wt., 14 maj 2019 o 19:08 Dominik <ddominiq@gmail.com> napisał(a):

**Comment by jjxtra** [comment]
I'd suggest just stopping the service, renaming the ipban folder to ipban_old and extracting the files to your ipban folder. Then if you want to replace just the DigitalRuby.IPBan.dll.config file you can, just copy the config file from your ipban_old folder.

**Comment by ddominq** [comment]
I not only copied but re-opened the catalog, and since the new version has
the program DigitalRuby.ipban erased and reinstalled the service for new
values, the only thing that stubbornly digs into the new folder is the
database of dances. The configuration file is now much larger so I change
it manually.

I copied the new version to the old one including config. At startup, it
deletes all IPs the same.
I set the time for eternity, again and the same.

in the message from 14 maj 2019, 19:08 It seems that the program does not
work


Dominik


wt., 14 maj 2019 o 19:20 Jeff Johnson <notifications@github.com> napisał(a):

**Comment by jjxtra** [comment]
I'm not seeing this on my server. I've tested and set both ban and expire time to 00:00:00:00. It is not forgetting or unbanning the ip addresses with the very latest download. Maybe you got a cached download instead of a fresh one? I've purged my CloudFlare cache. Can you try downloading the .zip again from an incognito Window?

**Comment by ddominq** [comment]
Where can I find the parameter responsible for the unwanted "time expired"
effect of 15s?
I checked that it had nothing to do with CycleTime
There is nothing more in the config with 15s
Dominik


wt., 14 maj 2019 o 19:28 Dominik <ddominiq@gmail.com> napisał(a):

**Comment by ddominq** [comment]
Thank you! It helped but ... now the program itself starts ... I did not
let it add to the sevices because after each replacement I have to delete
sevice and restart machine and create service but ...
  after logging in to the account. the program started 4 times (I ran
logfile.txt
There is no program in shell: Common Startup
nor in shell: Startup where I have a "AutorunsDisabled" lock
What's happening?

Dominik


wt., 14 maj 2019 o 19:43 Dominik <ddominiq@gmail.com> napisał(a):

**Comment by ddominq** [comment]
My mistake. No is perfect!
I checked works also on VNC !!! You are awesome !!!

Dominik


wt., 14 maj 2019 o 20:11 Dominik <ddominiq@gmail.com> napisał(a):

**Comment by jjxtra** [comment]
Awesome! Please visit https://ipban.com for more details about the pro version coming later this summer :) Glad you are secured!

**Comment by jjxtra** [comment]
This is now available in IPBan Pro, which is in beta testing currently. See https://ipban.com for more details.
